import Head from "next/head";
import React from "react";
import { Navbar } from '../ui';

interface Props {
	children: React.ReactNode;
}

export const Layout: React.FC<Props> = ({children}) => {
	return (
		<>
			<Head>
				<title>Cookie Master</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <nav>
                <Navbar />
            </nav>
			<main style={{padding: "50px 20px"}}>{children}</main>
		</>
	);
};
